//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brownie.Properties
{
    using System;

    // ... (attributes omitted for brevity)
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() { }

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("Brownie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap SelectSky => ((System.Drawing.Bitmap)(ResourceManager.GetObject("SelectSky", resourceCulture)));
        internal static System.Drawing.Bitmap SelectStar => ((System.Drawing.Bitmap)(ResourceManager.GetObject("SelectStar", resourceCulture)));
        internal static System.Drawing.Bitmap Sky => ((System.Drawing.Bitmap)(ResourceManager.GetObject("Sky", resourceCulture)));
        internal static System.Drawing.Bitmap Star => ((System.Drawing.Bitmap)(ResourceManager.GetObject("Star", resourceCulture)));
        internal static System.Drawing.Bitmap Werewolf => ((System.Drawing.Bitmap)(ResourceManager.GetObject("Werewolf", resourceCulture)));

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brownie
        {
            get
            {
                object obj = ResourceManager.GetObject("Brownie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
